name = "contasav"
compatibility_date = "2026-07-16"

# Le dice a Cloudflare que los archivos estáticos (index.html) están
# en la raíz del proyecto, no en una subcarpeta de build (dist, build, etc.)
pages_build_output_dir = "."
